name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fake deploy
        run: |
          echo "🚀 Деплой в прод (авто после merge в main)..."
          sleep 3
          echo "✅ Deploy успешный!"

      - name: Notify Telegram (success)
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: 7701325227
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: "🚀 Deploy успешный после merge в main!"

      - name: Notify Telegram (fail)
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: 7701325227
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: "❌ Deploy упал после merge в main!"
