name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fake deploy
        run: echo "🚀 Deploy successful!"

      - name: Notify Telegram
        uses: appleboy/telegram-action@master
        with:
          to: 7701325227
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: "✅ Deploy успешный!"
